#show all meals from database
show_meals:
  path: /all-meals
  controller: App\Controller\MealPlanShowAllMealsController::showAllMeals

add_new_ingredient:
  path: /shoppingList/addNew
  methods: POST
  controller: App\Controller\ShoppingListController::addNewIngredientUsingAjax

delete_ingredient_from_shopping_list:
  path: /shoppingList/delete/{id}
  methods: POST
  controller: App\Controller\ShoppingListController::deleteIngredientFromShoppingList

  #search by meal type
search_by_meal_type:
  path: /all-meals/type/{mealType}
  methods: GET
  controller: App\Controller\MealPlanSearchByMealTypeController::searchByMealType

  #search by meal name
search_by_meal_name:
  path: /all-meals/name/{mealName}
  methods: GET
  controller: App\Controller\MealPlanSearchByMealNameController::searchByMealName
#add new recipe to meal

add_new_recipe:
  path: /meal/{mealID}/add-new-recipe
  methods: POST
  controller: App\Controller\MealPlanAddNewRecipeToMealController::createNewRecipe
